services:
  #postgres:
  #  image: postgres:17.6
  #  container_name: postgres-db
  #  restart: unless-stopped
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: 12345
  #    POSTGRES_DB: testcase_llm_generator
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - pgdata_vol:/var/lib/postgresql/data
  #  networks:
  #    - testcase_llm_generator_net
  #  healthcheck:
  #    test: ["CMD-SHELL", "pg_isready -U postgres"]
  #    interval: 10s
  #    timeout: 5s
  #    retries: 5
  #    start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
      # BuildKit optimizations for faster builds
      cache_from:
        - type=local,src=/tmp/.buildx-cache
      cache_to:
        - type=local,dest=/tmp/.buildx-cache,mode=max
    container_name: tc-llm-generator-app
    restart: unless-stopped
    # environment:
    #   SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    #depends_on:
    #  postgres:
    #    condition: service_healthy
    networks:
      - testcase_llm_generator_net

volumes:
  pgdata_vol:

networks:
  testcase_llm_generator_net:
    driver: bridge
