spring:
  datasource:
    # Use postgres container name as host
    url: jdbc:postgresql://postgres:5432/testcase_llm_generator
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: PatientHikariCP
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: "SELECT 1"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
    show-sql: true
    open-in-view: false

  hateoas:
    use-hal-as-default-json-media-type: true

server:
  port: 8080
  shutdown: graceful

# SpringDoc configuration
springdoc:
  show-actuator: false
  use-management-port: false

jwt:
  secret: ${JWT_SECRET_KEY:i4QWPoQ64kLVJBtvNqun0wO8qQT99A7UZGqWOco_dSzhii7HOc8_Pk5YavXiDJrNOOFdlvUKxwuKIf5YcHjGsg}
  expiration-accessToken: ${ACCESS_TOKEN_EXPIRE:3600000}
  expiration-refreshToken: ${REFRESH_TOKEN_EXPIRE:604800000}

google:
  client-id: ${GOOGLE_CLIENT_ID:479445555768-ilmv6q2n3r4bk6mmt8d0j09pv1n1ket8.apps.googleusercontent.com}
