jwt:
  secret: ${JWT_SECRET_KEY}
  expiration-accessToken: ${ACCESS_TOKEN_EXPIRE}
  expiration-refreshToken: ${REFRESH_TOKEN_EXPIRE}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}
